import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

import Link from "next/link";

export default function Home() {
  const [data, setData] = useState([]);

  const getData = async () => {
    const res = await fetch("/api/posts");
    const resData = await res.json();
    setData(resData);
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {data.length == 0 ? <h1>Loading...</h1> : <Posts posts={data.posts} />}
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

const Posts = ({ posts }) => {
  console.log(posts);
  return (
    <>
      <h1 className='font-bold text-4xl mb-6'>Here are the posts</h1>
      <Link href='/create'>
        <a className='bg-blue-400 px-4 py-2 mb-4 text-white'>
          Create new post...
        </a>
      </Link>
      {posts && posts.map((post) => <Post key={post.id} post={post} />)}
    </>
  );
};

const Post = ({ post }) => {
  return (
    <div className='bg-green-400 w-4/5 mb-2 p-4'>
      <div className='text-xl font-bold'>{post.title}</div>
      <div>{post.content}</div>
    </div>
  );
};
